[package]
name = "lua-async-http"
version = "0.1.0"
authors = ["Lucien Greathouse <me@lpghatguy.com>"]

[lib]
name = "async_http"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"
lua51-sys = "0.1"
reqwest = "0.8.8"
lazy_static = "1.0"
